version: 2
jobs:
  build:
    docker:
      - image: debian:testing
    steps:
      - run:
         name: setup
         command: apt-get update && apt-get install -y unzip git gfortran cmake gcc g++ texlive
      - checkout
      - run:
          name: build and test
          command: |
             git submodule update --init lib/NAFFlib
             ./cmake_six BUILD_TESTING 
             cd build/*BUILD_TESTING*
             make -j4
             ctest -j4 -L fast
